# This is a basic workflow to help you get started with Actions

name: .NET Setup CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  deployment: 
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.1.2
      with:
    # SDK version to use. Example: 2.2.104
       dotnet-version: 3.1.2 # optional
    # Optional package source for which to set up authentication. Will consult any existing NuGet.config in the root of the repo and provide a temporary NuGet.config using the NUGET_AUTH_TOKEN environment variable as a ClearTextPassword
       source-url: Microsoft.AspNetCore.Identity # optional
    # Optional OWNER for using packages from GitHub Package Registry organizations/users other than the current repository's owner. Only used if a GPR URL is also provided in source-url
   #    owner: # optional
    # Optional NuGet.config location, if your NuGet.config isn't located in the root of the repo.
       config-file: nuget.config # optional
    # Deprecated. Use dotnet-version instead. Will not be supported after October 1, 2019
#
